global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django_hiretrack'
    scheme: https
    metrics_path: '/metrics/'
    bearer_token: 'hiretrack_secret_metrics_token_2026'
    static_configs:
      - targets: ['hiretrack-gw0m.onrender.com']
