# Generated by Django 5.2.13 on 2026-04-08 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_applied', models.DateField()),
                ('company', models.CharField(max_length=255)),
                ('role', models.CharField(max_length=255)),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
