# Generated by Django 5.2.13 on 2026-04-08 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_referral_job_date_job_person_name_alter_job_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='date',
        ),
        migrations.RemoveField(
            model_name='job',
            name='person_name',
        ),
        migrations.AddField(
            model_name='referral',
            name='company',
            field=models.CharField(default='2024-01-01', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='person_name',
            field=models.CharField(default='temp', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='referral',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('replied', 'Replied'), ('no_response', 'No Response')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('applied', 'Applied'), ('pending', 'Pending'), ('rejected', 'Rejected'), ('selected', 'Selected')], default='applied', max_length=20),
        ),
    ]
