# Generated by Django 5.2.13 on 2026-04-10 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_remove_job_date_remove_job_person_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
