# Generated by Django 5.2.13 on 2026-04-11 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_referral_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='referral',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
