# Generated by Django 5.2.13 on 2026-04-12 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_job_follow_up_date_referral_follow_up_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='is_starred',
            field=models.BooleanField(default=False),
        ),
    ]
