# Generated by Django 5.2.13 on 2026-04-30 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0011_job_platform_job_salary_range_referral_linkedin'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='cover_letter_file',
            field=models.FileField(blank=True, null=True, upload_to='job_documents/cover_letters/'),
        ),
        migrations.AddField(
            model_name='job',
            name='resume_file',
            field=models.FileField(blank=True, null=True, upload_to='job_documents/resumes/'),
        ),
    ]
