# Generated by Django 5.2.13 on 2026-05-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0016_scribble'),
    ]

    operations = [
        migrations.AddField(
            model_name='scribble',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to='scribble_files/'),
        ),
    ]
