# Generated by Django 5.2.13 on 2026-05-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0017_scribble_attached_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scribble',
            name='attached_file',
        ),
    ]
