# Generated by Django 5.2.13 on 2026-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0019_create_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='notification_dismissed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='referral',
            name='notification_dismissed',
            field=models.BooleanField(default=False),
        ),
    ]
